# site settings
title: "Iby Waks"
subtitle: About me & portfolio
email: ibywaks@gmail.com
description: "Iby's site"
baseurl: "/" # the subpath of your site, e.g. /blog
url: "ibywaks.github.io" # the base hostname & protocol for your site
author: "Ibiyemi Adewakun"
# street_address: 1234 Somewhere Road
city: Lagos
# state: Lagos
# zip_code: 55555
country: Nigeria
# phone: (716) 555-5555

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 6

# social settings (key must match name of font awesome icon)
# see https://fontawesome.com/icons?d=gallery&p=2&s=brands
# Icons are not shown if value is empty
# You need to restart jekyll for changes to have an effect
socials:
  GitHub: https://github.com/ibywaks
  LinkedIn: https://www.linkedin.com/in/ibiyemi-adewakun-13139a144/
  # GitLab:
  # Google-Plus: https://plus.google.com/u/0/+AndrewBanchich
  # Instagram:
  # Twitter: https://twitter.com/andrewbanchich
  # Facebook:
  # Slack:

# build settings
markdown: kramdown

sass:
  style: compressed

exclude:
- "*.gemspec"
- LICENSE.md
- CONTRIBUTING.md
- README.md 
